apiVersion: v2
name: ez-platform
description: EZ Developer Portal on AWS
type: application
version: 0.1.0
appVersion: "1.0.0"

annotations:
  backstage.io/kubernetes-id: ez-platform
  ez.platform/tier: platform
  ez.platform/team: platform
