replicaCount: 1

image:
  pullPolicy: Always

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi
