image:
  repository: ""
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 70

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi

service:
  type: ClusterIP
  port: 80
  targetPort: 7007

ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
  host: ""
  path: /

env:
  APP_BASE_URL: "http://placeholder.local"
  BACKEND_BASE_URL: "http://placeholder.local"

existingSecret: ez-platform-env

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

containerSecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop: ["ALL"]

serviceAccount:
  create: true
  annotations: {}

podDisruptionBudget:
  enabled: true
  minAvailable: 1

global:
  environment: ""
  commitSha: ""
