# dev environment overrides
replicaCount: 1

autoscaling:
  enabled: false

resources:
  requests:
    cpu:    "50m"
    memory: "64Mi"
  limits:
    cpu:    "200m"
    memory: "256Mi"

ingress:
  enabled:   true
  className: "alb"
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  host:      ""

env:
  APP_ENV: "dev"
