# prod environment overrides
replicaCount: 3

autoscaling:
  enabled:     true
  minReplicas: 3
  maxReplicas: 20

resources:
  requests:
    cpu:    "200m"
    memory: "256Mi"
  limits:
    cpu:    "1000m"
    memory: "1Gi"

ingress:
  enabled:   true
  className: "alb"
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  host:      ""

env:
  APP_ENV: "production"
