# dev environment overrides
replicaCount: 1

autoscaling:
  enabled: false

resources:
  requests:
    cpu:    "50m"
    memory: "64Mi"
  limits:
    cpu:    "200m"
    memory: "256Mi"

ingress:
  enabled:   true
  className: "nginx"
  host:      "${{ values.name }}.dev.internal"

env:
  APP_ENV: "dev"
