"""
${{ values.name }} — EZ Lite Service

Generated by the EZ Platform Golden Path.
Team: ${{ values.team }}
Tier: lite (stateless)
"""
import logging
import os

from fastapi import FastAPI
from fastapi.responses import JSONResponse
import uvicorn

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(name)s — %(message)s",
)
logger = logging.getLogger(__name__)

app = FastAPI(
    title="${{ values.name }}",
    description="EZ Lite service — ${{ values.description }}",
    version=os.getenv("APP_VERSION", "dev"),
)


@app.get("/healthz", include_in_schema=False)
def healthz():
    """Liveness probe — returns 200 if the process is running."""
    return {"status": "ok"}


@app.get("/readyz", include_in_schema=False)
def readyz():
    """Readiness probe — returns 200 if the service is ready to serve traffic."""
    return {"status": "ready"}


@app.get("/")
def root():
    return {
        "service": "${{ values.name }}",
        "team":    "${{ values.team }}",
        "version": os.getenv("APP_VERSION", "dev"),
        "env":     os.getenv("APP_ENV", "local"),
    }


if __name__ == "__main__":
    port = int(os.getenv("PORT", "8080"))
    uvicorn.run("main:app", host="0.0.0.0", port=port, log_level="info")
