"""
${{ values.name }} — EZ Standard Service

Generated by the EZ Platform Golden Path.
Team: ${{ values.team }}
Tier: standard (stateful — DB + secrets)
"""
import logging
import os

from fastapi import FastAPI, HTTPException
from fastapi.responses import JSONResponse
import uvicorn

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(name)s — %(message)s",
)
logger = logging.getLogger(__name__)

app = FastAPI(
    title="${{ values.name }}",
    description="EZ Standard service — ${{ values.description }}",
    version=os.getenv("APP_VERSION", "dev"),
)

# ── Database connection (injected from External Secrets Operator) ─────────────
DATABASE_URL = os.getenv("DATABASE_URL")  # Set via ESO from AWS Secrets Manager


@app.on_event("startup")
async def startup():
    logger.info("Starting %s (env=%s)", "${{ values.name }}", os.getenv("APP_ENV"))
    if DATABASE_URL:
        logger.info("Database URL configured (host masked for security)")
    else:
        logger.warning("DATABASE_URL not set — DB features unavailable")


@app.get("/healthz", include_in_schema=False)
def healthz():
    """Liveness probe."""
    return {"status": "ok"}


@app.get("/readyz", include_in_schema=False)
def readyz():
    """Readiness probe — checks DB connectivity."""
    if DATABASE_URL is None:
        # In environments without DB (e.g. CI), skip DB check
        return {"status": "ready", "db": "skipped"}
    # Add real DB connectivity check here
    return {"status": "ready", "db": "ok"}


@app.get("/")
def root():
    return {
        "service": "${{ values.name }}",
        "team":    "${{ values.team }}",
        "version": os.getenv("APP_VERSION", "dev"),
        "env":     os.getenv("APP_ENV", "local"),
    }
